spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:doyouremember
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  web:
    resources:
      add-mappings: true

server:
  port: 8080
  servlet:
    context-path: /

file:
  upload:
    location: ${FILE_UPLOAD_PATH:./uploads}

spring.web.resources.add-mappings: true

web:
  resources:
    static-locations: classpath:/static/ 